# Generated by Django 3.2.18 on 2023-05-23 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationsmessage',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='conversationsmessage',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='ConversationsMessage',
        ),
    ]
