# Generated by Django 3.2.18 on 2023-05-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0040_ads_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='first_ads_images',
            field=models.ImageField(default='', upload_to='ads_list/'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='symbol',
            field=models.BooleanField(default=False),
        ),
    ]
