# Generated by Django 3.2.18 on 2023-05-14 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0041_auto_20230513_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='ads_id',
            field=models.ForeignKey(blank=True, db_column='ads_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.ads'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user_id',
            field=models.ForeignKey(blank=True, db_column='uid', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
