# Generated by Django 3.2.18 on 2023-05-15 14:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0042_auto_20230514_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='symbol',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
