# Generated by Django 3.2.18 on 2023-05-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0044_auto_20230517_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='adsForWhichGender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('A', 'All')], max_length=1, null=True),
        ),
    ]
