# Generated by Django 3.2.18 on 2023-05-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0045_ads_adsforwhichgender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='location',
            field=models.CharField(choices=[('Rajkot', 'Raj'), ('Morbi', 'Mor'), ('Jamnagar', 'Jam'), ('Junagadh', 'Jun'), ('Gandhinagar', 'GNR'), ('Gandhidham', 'Gandhidham, Kutch'), ('Bedi', 'Bedi, Rajkot'), ('Chotila', 'Chotila, Rajkot'), ('Gondal', 'gondal')], max_length=20, null=True),
        ),
    ]
