# Generated by Django 3.2.18 on 2023-05-21 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0046_alter_ads_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ads',
            options={'ordering': ['-time']},
        ),
    ]
