# Generated by Django 3.2.18 on 2023-05-21 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0047_alter_ads_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ads',
            options={},
        ),
    ]
