# Generated by Django 3.2.18 on 2023-05-21 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0048_alter_ads_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='time',
        ),
        migrations.AlterField(
            model_name='ads',
            name='listed_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
