# Generated by Django 3.2.18 on 2023-05-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0049_auto_20230521_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='ads_description',
            field=models.TextField(blank=True, max_length=450),
        ),
    ]
