# Generated by Django 3.2.18 on 2023-05-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0050_alter_ads_ads_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='listed_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
