# Generated by Django 3.2.18 on 2023-05-23 20:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0051_alter_ads_listed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
