# Generated by Django 3.2.18 on 2023-05-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20230505_0205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mobile_is_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='clg_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
